version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0

  pre_build:
    commands:
      - dotnet restore AWS/AWS.csproj

  build:
    commands:
      - dotnet build AWS/AWS.csproj -c Release

  post_build:
    commands:
      - dotnet publish AWS/AWS.csproj -c Release -o publish

artifacts:
  files:
    - '**/*'
  base-directory: publish